name: Feed update
on:
  push:
    branches:
      - main

jobs:
  make_posts:
    name: Make posts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          python3 -m pip install -r ./src/requirements.txt
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Check for feed and post
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ "${changed_file}" == *".json"* ]]; then
              python3 ./src/main.py --post_file "${changed_file}"
            else
              echo "skipping ${changed_file}"
            fi
          done
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.ACCESS_TOKEN }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.CONSUMER_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.CONSUMER_SECRET }}